site_name: KennieLetterIndexBar文档
site_author: kennie
site_description: 字母索引导航
copyright: Copyright &copy; 2021 kennie

repo_name: Github
repo_url: https://github.com/kennielab/KennieLetterIndexBar

docs_dir: 'docs'

theme:
  name: material
  
nav:
  - 使用: index.md
  - 开发日志: DEVLOG.md
  - 更新日志: UPDATELOG.md
